INSERT INTO BKG_CSTMS_PNM_VVD (
	VSL_CD,
	SKD_VOY_NO,
	SKD_DIR_CD,
	POL_CD,
	POD_CD,
	ETA_DT,
	SLAN_CD,
	SHP_ID_NO,
	VST_NO,
	MVMT_SEQ,
	PNM_VSL_OPR_CD,
	PNM_ORG_CD,
	PNM_DEST_CD,
	CRE_USR_ID,
	CRE_DT,
	UPD_USR_ID,
	UPD_DT
) VALUES( 
	@[vsl_cd],
	@[skd_voy_no],
	@[skd_dir_cd],
	@[pol_cd],
	@[pod_cd],
	TO_DATE(@[vps_eta_dt], 'YYYY-MM-DD hh24:mi'),
	@[slan_cd],
	@[shp_id_no],
	@[vst_no],
	@[mvmt_seq],
	@[pnm_vsl_opr_cd],
	@[pnm_org_cd],
	@[pnm_dest_cd],
	@[cre_usr_id],
	SYSDATE,
	@[cre_usr_id],
	SYSDATE
)